source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3'
gem 'pry'
gem 'activerecord-reset-pk-sequence', '~> 0.2.1'
gem 'faker', '~> 2.13'
gem 'tty-prompt', '~> 0.22.0'
gem 'require_relative', '~> 1.0', '>= 1.0.3'